--TB_COMPANY--
INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, NATION, REGION) VALUES (1, '원티드랩', '한국', '서울');
INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, NATION, REGION) VALUES (2, '원티드코리아', '한국', '부산');
INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, NATION, REGION) VALUES (3, '카카오', '한국', '판교');
INSERT INTO TB_COMPANY (COMPANY_ID, COMPANY_NAME, NATION, REGION) VALUES (4, '네이버', '한국', '판교');

--TB_MEMBER--
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_EMAIL, PASSWORD) VALUES (1, 'user1@google.com', 'abcdefgh');
INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_EMAIL, PASSWORD) VALUES (2, 'user2@google.com', 'abcdefgh');